name: Java Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
        testgroup: [
          # Includes everything in tests/ except the ones listed here
          '**/*,!com.google.genai.ClientTest,!com.google.genai.TableTest,!com.google.genai.HttpApiClientTest,!com.google.genai.ModelsTest,!com.google.genai.OperationsTest'
        ]
    name: unit-test (${{matrix.java}})
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{matrix.java}}
        cache: 'maven'
    - name: Java Unit Tests
      run: mvn clean test -Dtest=${{matrix.testgroup}}
      env:
        GOOGLE_API_KEY: testkey
