# This workflow runs a simple test to verify we are supporing the required Java versions.
name: validation

on:
  pull_request:
    branches:
      - main

jobs:
  java-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11', '17', '21']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Compile ${{ matrix.java-version }}
        run: mvn clean compile